# We have a conf and classes directory, add to BBPATH

BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "mxt-rzv2n"
BBFILE_PATTERN_mxt-rzv2n := "^${LAYERDIR}/"

BBFILE_PRIORITY_mxt-rzv2n = "20"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*.bb \
    ${LAYERDIR}/recipes-*/*.bbappend \
    ${LAYERDIR}/recipes-*/*/*.bbappend"

LAYERDEPENDS_meta-rz-bsp = "meta-rz-bsp "
LAYERSERIES_COMPAT_mxt-rzv2n = "scarthgap"
